name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run linting
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Run tests
        run: go test -v ./...

      - name: Build application
        run: go build -v -o calculator


      # # Build and Push Docker Image to Google Artifact Registry
      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v2

      # - name: Authenticate to GCP
      #   uses: google-github-actions/auth@v0
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # - name: Configure Docker for Artifact Registry
      #   run: |
      #     gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_HOST }} --quiet

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY_HOST }}/$GCP_PROJECT_ID/calculator:${{ github.sha }} .

      # - name: Push Docker image to Artifact Registry
      #   run: |
      #     docker push ${{ secrets.GCP_ARTIFACT_REGISTRY_HOST }}/$GCP_PROJECT_ID/calculator:${{ github.sha }}

      # # Create Helm Chart Package and Push it to Artifact Registry
  
      # - name: Package Helm chart
      #   run: |
      #     helm package ./my-helm-chart --destination ./helm-packages

      # - name: Push Helm chart to Artifact Registry
      #   run: |
      #     helm push ./helm-packages/calculator-*.tgz oci://${{ secrets.GCP_ARTIFACT_REGISTRY_HOST }}/$GCP_PROJECT_ID/helm-charts

      # # Deployment Steps
      # - name: Set up kubectl
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     region: ${{ secrets.GCP_REGION }}
      #     cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}

      # - name: Deploy Helm Chart to GKE from Artifact Registry
      #   run: |
      #     helm repo add my-chart-repo oci://${{ secrets.GCP_ARTIFACT_REGISTRY_HOST }}/$GCP_PROJECT_ID/helm-charts
      #     helm repo update
      #     helm upgrade --install calculator my-chart-repo/calculator  --values ./my-helm-chart/values.yaml
